#!/usr/bin/env python3
"""
INITIALLY GENERATED BY LLM
Nmap GUI Tool - Cross-platform pentesting utility
Works on Linux, Windows, and MacOS

Automatically requests the root/admin password for commands that require elevation, e.g.:

* TCP SYN scan (-sS)
* ACK scan (-sA)
* OS detection (-O)
* UDP scans (-sU)
* Firewall mapping (-sA, -sF, etc.)
* NSE scripts (--script)
"""

import tkinter as tk
from tkinter import ttk, scrolledtext, messagebox, filedialog
import subprocess
import threading
from pathlib import Path
import sys
import platform
import os
import shutil

class NmapGUI:
    def __init__(self, root):
        self.root = root
        self.root.title("Nmap Scanner")
        self.root.geometry("1100x750")

        # Check if nmap is installed
        self.nmap_available = self._check_nmap()
        if not self.nmap_available:
            messagebox.showwarning(
                "Nmap Not Found",
                "nmap is not installed or not in PATH.\n"
                "Please install nmap to use this tool.\n\n"
                "Linux: sudo apt install nmap\n"
                "Windows: Download from nmap.org or use: choco install nmap\n"
                "macOS: brew install nmap"
            )

        self.process = None
        self.is_running = False

        self._setup_styles()
        self._build_ui()

    def _check_nmap(self):
        """Check if nmap is available"""
        try:
            subprocess.run(['nmap', '--version'],
                         capture_output=True,
                         timeout=2,
                         check=False)
            return True
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def _setup_styles(self):
        """Configure color scheme and styles"""
        style = ttk.Style()

        # Define color palette
        self.bg_color = "#1e1e1e"
        self.fg_color = "#e0e0e0"
        self.accent_color = "#0d7377"
        self.danger_color = "#d32f2f"
        self.section_bg = "#2d2d2d"

        # Configure root window
        self.root.configure(bg=self.bg_color)

        # Configure style for ttk widgets
        style.theme_use('clam')
        style.configure('TFrame', background=self.bg_color)
        style.configure('TLabelframe', background=self.bg_color, foreground=self.fg_color)
        style.configure('TLabelframe.Label', background=self.bg_color, foreground=self.fg_color)
        style.configure('TLabel', background=self.bg_color, foreground=self.fg_color)
        style.configure('TCheckbutton', background=self.bg_color, foreground=self.fg_color)
        style.configure('TRadiobutton', background=self.bg_color, foreground=self.fg_color)
        style.configure('Accent.TButton', foreground=self.fg_color)

    def _build_ui(self):
        """Build the main UI"""
        # Main container with scrollbar
        main_frame = ttk.Frame(self.root)
        main_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)

        # Create canvas and scrollbar for left panel
        left_frame = ttk.Frame(main_frame)
        left_frame.pack(side=tk.LEFT, fill=tk.BOTH, expand=True, padx=(0, 10))

        canvas = tk.Canvas(left_frame, bg=self.bg_color, highlightthickness=0)
        scrollbar = ttk.Scrollbar(left_frame, orient=tk.VERTICAL, command=canvas.yview)
        scrollable_frame = ttk.Frame(canvas)

        scrollable_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
        )

        canvas.create_window((0, 0), window=scrollable_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)

        canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        # Build sections
        self._build_target_section(scrollable_frame)
        self._build_scan_type_section(scrollable_frame)
        self._build_port_section(scrollable_frame)
        self._build_detection_section(scrollable_frame)
        self._build_options_section(scrollable_frame)
        self._build_nse_section(scrollable_frame)
        self._build_output_section(scrollable_frame)
        self._build_button_section(scrollable_frame)

        # Right panel - output
        self._build_output_panel(main_frame)

    def _build_target_section(self, parent):
        """Target specification"""
        frame = ttk.LabelFrame(parent, text="Target", padding=10)
        frame.pack(fill=tk.X, pady=5)

        ttk.Label(frame, text="Host/IP/Range:").grid(row=0, column=0, sticky=tk.W, pady=5)
        self.target_entry = ttk.Entry(frame, width=40)
        self.target_entry.grid(row=0, column=1, sticky=tk.EW, padx=5)
        self.target_entry.insert(0, "192.168.1.0/24")
        self.target_entry.bind("<KeyRelease>", lambda e: self._update_command_display())
        frame.columnconfigure(1, weight=1)

        ttk.Label(frame, text="Examples: 192.168.1.1 | 10.0.0.0/24 | example.com",
                 foreground="#888888").grid(row=1, column=0, columnspan=2, sticky=tk.W)

        # Load targets from file
        def load_file():
            file = filedialog.askopenfilename(filetypes=[("Text files", "*.txt"), ("All", "*.*")])
            if file:
                self.target_entry.delete(0, tk.END)
                self.target_entry.insert(0, f"--iL {file}")
                self._update_command_display()

        ttk.Button(frame, text="Load from File", command=load_file).grid(row=0, column=2, padx=5)

    def _build_scan_type_section(self, parent):
        """Scan type selection"""
        frame = ttk.LabelFrame(parent, text="Scan Type", padding=10)
        frame.pack(fill=tk.X, pady=5)

        self.scan_type = tk.StringVar(value="-sS")
        self.scan_type.trace("w", lambda *args: self._update_command_display())

        scans = [
            ("-sS", "TCP SYN (half-open, stealthy)"),
            ("-sT", "TCP Connect (full connection)"),
            ("-sU", "UDP Scan"),
            ("-sA", "ACK Scan (firewall mapping)"),
            ("-sn", "Ping Sweep (host discovery only)"),
        ]

        for i, (flag, desc) in enumerate(scans):
            row = i // 2
            col = i % 2
            ttk.Radiobutton(frame, text=desc, variable=self.scan_type,
                          value=flag).grid(row=row, column=col, sticky=tk.W, padx=10, pady=3)

    def _build_port_section(self, parent):
        """Port specification"""
        frame = ttk.LabelFrame(parent, text="Ports", padding=10)
        frame.pack(fill=tk.X, pady=5)

        ttk.Label(frame, text="Port Range:").grid(row=0, column=0, sticky=tk.W)
        self.port_entry = ttk.Entry(frame, width=30)
        self.port_entry.grid(row=0, column=1, sticky=tk.EW, padx=5)
        self.port_entry.insert(0, "1-1000")
        self.port_entry.bind("<KeyRelease>", lambda e: self._update_command_display())
        frame.columnconfigure(1, weight=1)

        ttk.Label(frame, text="Leave blank for common ports",
                 foreground="#888888").grid(row=1, column=0, columnspan=2, sticky=tk.W)

        # Quick buttons
        def set_ports(ports):
            self.port_entry.delete(0, tk.END)
            self.port_entry.insert(0, ports)
            self._update_command_display()

        ttk.Button(frame, text="All (-)",
                  command=lambda: set_ports("-")).grid(row=0, column=2, padx=2)
        ttk.Button(frame, text="Top 100",
                  command=lambda: set_ports("--top-ports 100")).grid(row=0, column=3, padx=2)
        ttk.Button(frame, text="Web",
                  command=lambda: set_ports("80,443,8000,8080,8443")).grid(row=0, column=4, padx=2)

    def _build_detection_section(self, parent):
        """Version and OS detection"""
        frame = ttk.LabelFrame(parent, text="Detection Options", padding=10)
        frame.pack(fill=tk.X, pady=5)

        self.version_detection = tk.BooleanVar()
        self.version_detection.trace("w", lambda *args: self._update_command_display())
        self.os_detection = tk.BooleanVar()
        self.os_detection.trace("w", lambda *args: self._update_command_display())
        self.aggressive = tk.BooleanVar()
        self.aggressive.trace("w", lambda *args: self._update_command_display())

        ttk.Checkbutton(frame, text="Service Version Detection (-sV)",
                       variable=self.version_detection).pack(anchor=tk.W, pady=3)
        ttk.Checkbutton(frame, text="OS Detection (-O)",
                       variable=self.os_detection).pack(anchor=tk.W, pady=3)
        ttk.Checkbutton(frame, text="Aggressive Scan (-A)",
                       variable=self.aggressive).pack(anchor=tk.W, pady=3)

    def _build_options_section(self, parent):
        """Timing and other options"""
        frame = ttk.LabelFrame(parent, text="Timing & Options", padding=10)
        frame.pack(fill=tk.X, pady=5)

        # Timing
        ttk.Label(frame, text="Timing:").grid(row=0, column=0, sticky=tk.W)
        self.timing = tk.StringVar(value="")
        self.timing.trace("w", lambda *args: self._update_command_display())
        timing_options = [
            ("Default", ""),
            ("T1 (Sneaky)", "-T1"),
            ("T2 (Polite)", "-T2"),
            ("T4 (Aggressive)", "-T4"),
            ("T5 (Insane)", "-T5"),
        ]

        timing_menu = ttk.Combobox(frame, textvariable=self.timing,
                                   values=[t[0] for t in timing_options],
                                   state="readonly", width=20)
        timing_menu.grid(row=0, column=1, sticky=tk.EW, padx=5)

        # Store mapping
        self.timing_map = {t[0]: t[1] for t in timing_options}

        frame.columnconfigure(1, weight=1)

        # Options
        self.no_ping = tk.BooleanVar()
        self.no_ping.trace("w", lambda *args: self._update_command_display())
        self.verbose = tk.BooleanVar()
        self.verbose.trace("w", lambda *args: self._update_command_display())
        self.disable_dns = tk.BooleanVar()
        self.disable_dns.trace("w", lambda *args: self._update_command_display())

        ttk.Checkbutton(frame, text="Skip Ping (-Pn)",
                       variable=self.no_ping).grid(row=1, column=0, columnspan=2, sticky=tk.W, pady=3)
        ttk.Checkbutton(frame, text="Verbose Output (-v)",
                       variable=self.verbose).grid(row=2, column=0, columnspan=2, sticky=tk.W, pady=3)
        ttk.Checkbutton(frame, text="Disable DNS Resolution (-n)",
                       variable=self.disable_dns).grid(row=3, column=0, columnspan=2, sticky=tk.W, pady=3)

    def _build_nse_section(self, parent):
        """NSE script options"""
        frame = ttk.LabelFrame(parent, text="NSE Scripts", padding=10)
        frame.pack(fill=tk.X, pady=5)

        self.default_scripts = tk.BooleanVar()
        self.default_scripts.trace("w", lambda *args: self._update_command_display())
        self.vuln_scripts = tk.BooleanVar()
        self.vuln_scripts.trace("w", lambda *args: self._update_command_display())
        self.auth_scripts = tk.BooleanVar()
        self.auth_scripts.trace("w", lambda *args: self._update_command_display())

        ttk.Checkbutton(frame, text="Default Scripts (-sC)",
                       variable=self.default_scripts).pack(anchor=tk.W, pady=3)
        ttk.Checkbutton(frame, text="Vulnerability Scripts (--script vuln)",
                       variable=self.vuln_scripts).pack(anchor=tk.W, pady=3)
        ttk.Checkbutton(frame, text="Auth Scripts (--script auth)",
                       variable=self.auth_scripts).pack(anchor=tk.W, pady=3)

        ttk.Label(frame, text="Custom Script:").pack(anchor=tk.W, pady=(10, 3))
        self.custom_script = ttk.Entry(frame)
        self.custom_script.pack(fill=tk.X, pady=3)
        self.custom_script.insert(0, "e.g., smb-*,ssh-*")
        self.custom_script.bind("<KeyRelease>", lambda e: self._update_command_display())

    def _build_output_section(self, parent):
        """Output format options"""
        frame = ttk.LabelFrame(parent, text="Output Format", padding=10)
        frame.pack(fill=tk.X, pady=5)

        self.output_format = tk.StringVar(value="")
        self.output_format.trace("w", lambda *args: self._update_command_display())

        ttk.Label(frame, text="Save Output As:").grid(row=0, column=0, sticky=tk.W)
        self.output_file = ttk.Entry(frame, width=30)
        self.output_file.grid(row=0, column=1, sticky=tk.EW, padx=5)
        self.output_file.bind("<KeyRelease>", lambda e: self._update_command_display())
        frame.columnconfigure(1, weight=1)

        formats = [
            ("None", ""),
            ("Text (-o)", "-o"),
            ("Greppable (-oG)", "-oG"),
            ("XML (-oX)", "-oX"),
            ("All Formats (-oA)", "-oA"),
        ]

        format_menu = ttk.Combobox(frame, textvariable=self.output_format,
                                   values=[f[0] for f in formats],
                                   state="readonly", width=20)
        format_menu.grid(row=0, column=2, padx=5)
        self.format_map = {f[0]: f[1] for f in formats}

    def _build_button_section(self, parent):
        """Action buttons"""
        frame = ttk.Frame(parent)
        frame.pack(fill=tk.X, pady=15)

        self.scan_button = ttk.Button(frame, text="▶ Start Scan", command=self._start_scan)
        self.scan_button.pack(side=tk.LEFT, padx=5)

        self.stop_button = ttk.Button(frame, text="⏹ Stop Scan", command=self._stop_scan,
                                     state=tk.DISABLED)
        self.stop_button.pack(side=tk.LEFT, padx=5)

        ttk.Button(frame, text="Clear Output", command=self._clear_output).pack(side=tk.LEFT, padx=5)
        ttk.Button(frame, text="Copy Command", command=self._copy_command).pack(side=tk.LEFT, padx=5)

    def _build_output_panel(self, parent):
        """Output panel on the right"""
        frame = ttk.LabelFrame(parent, text="Output", padding=10)
        frame.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True, padx=(10, 0))

        # Command display
        ttk.Label(frame, text="Command:").pack(anchor=tk.W, pady=(0, 5))
        self.command_display = tk.Text(frame, height=2, width=50,
                                       bg=self.section_bg, fg="#00ff00",
                                       font=("Courier", 9), wrap=tk.WORD,
                                       state=tk.DISABLED)
        self.command_display.pack(fill=tk.X, pady=(0, 10))

        # Output text
        ttk.Label(frame, text="Scan Results:").pack(anchor=tk.W, pady=(0, 5))
        self.output_text = scrolledtext.ScrolledText(frame, height=30, width=50,
                                                     bg=self.section_bg,
                                                     fg=self.fg_color,
                                                     font=("Courier", 9))
        self.output_text.pack(fill=tk.BOTH, expand=True)

        # Status bar
        self.status_var = tk.StringVar(value="Ready")
        status_bar = ttk.Label(parent, textvariable=self.status_var, relief=tk.SUNKEN)
        status_bar.pack(side=tk.BOTTOM, fill=tk.X, padx=10, pady=(10, 0))

        # Initial command display
        self._update_command_display()

    def _build_command(self):
        """Build the nmap command from GUI selections"""
        cmd = ["nmap"]

        # Add target
        target = self.target_entry.get().strip()
        if not target:
            return ["nmap", "<target>"]

        # Add scan type
        cmd.append(self.scan_type.get())

        # Add ports
        ports = self.port_entry.get().strip()
        if ports:
            if ports.startswith("--"):
                cmd.append(ports)
            else:
                cmd.extend(["-p", ports])

        # Add detection options
        if self.version_detection.get():
            cmd.append("-sV")
        if self.os_detection.get():
            cmd.append("-O")
        if self.aggressive.get():
            cmd.append("-A")

        # Add timing
        timing = self.timing_map.get(self.timing.get())
        if timing:
            cmd.append(timing)

        # Add options
        if self.no_ping.get():
            cmd.append("-Pn")
        if self.verbose.get():
            cmd.append("-v")
        if self.disable_dns.get():
            cmd.append("-n")

        # Add NSE scripts
        if self.default_scripts.get():
            cmd.append("-sC")
        if self.vuln_scripts.get():
            cmd.append("--script vuln")
        if self.auth_scripts.get():
            cmd.append("--script auth")

        custom = self.custom_script.get().strip()
        if custom and not custom.startswith("e.g."):
            cmd.append(f"--script {custom}")

        # Add output format
        output_fmt = self.format_map.get(self.output_format.get())
        output_file = self.output_file.get().strip()
        if output_fmt and output_file:
            cmd.append(f"{output_fmt} {output_file}")

        # Add target (after command options)
        if target.startswith("--iL"):
            cmd.append(target)
        else:
            cmd.append(target)

        return cmd

    def _update_command_display(self):
        """Update the command display in real-time"""
        cmd = self._build_command()
        cmd_str = " ".join(cmd)
        self.command_display.config(state=tk.NORMAL)
        self.command_display.delete(1.0, tk.END)
        self.command_display.insert(1.0, cmd_str)
        self.command_display.config(state=tk.DISABLED)

    def _start_scan(self):
        """Start the nmap scan"""
        if not self.nmap_available:
            messagebox.showerror("Error", "nmap is not installed")
            return

        target = self.target_entry.get().strip()
        if not target:
            messagebox.showerror("Error", "Please enter a target")
            return

        cmd = self._build_command()

        # Clear output
        self.output_text.delete(1.0, tk.END)
        self.status_var.set("Running scan...")
        self.scan_button.config(state=tk.DISABLED)
        self.stop_button.config(state=tk.NORMAL)
        self.is_running = True

        # Run in thread
        thread = threading.Thread(target=self._run_scan, args=(cmd,), daemon=True)
        thread.start()

    def _needs_sudo(self, cmd):
        """Check if the nmap command needs elevated privileges"""
        # These scan types require root/admin
        privileged_scans = ['-sS', '-sA', '-sF', '-sN', '-sX', '-sU', '-O', '--script']

        cmd_str = " ".join(cmd)
        for scan in privileged_scans:
            if scan in cmd_str:
                # Check if already running as root/admin
                if platform.system() != "Windows":
                    try:
                        if os.geteuid() == 0:  # Already root
                            return False
                    except AttributeError:
                        pass
                return True

        return False

    def _run_with_elevation(self, cmd):
        """Run command with sudo/elevation"""
        try:
            if platform.system() == "Windows":
                # Windows: use runas via powershell
                cmd_str = " ".join(cmd)
                # We can't easily stream output from elevated process on Windows
                messagebox.showwarning("Elevation Required",
                    f"This scan requires administrator privileges.\n\n"
                    f"Please run this command in an elevated (Admin) command prompt:\n\n"
                    f"{cmd_str}")
                return None
            else:
                # Linux/macOS: use pkexec if available, fall back to sudo
                if shutil.which('pkexec'):
                    elevated_cmd = ['pkexec'] + cmd
                    use_pkexec = True
                else:
                    elevated_cmd = ['sudo'] + cmd
                    use_pkexec = False

                if use_pkexec:
                    self.output_text.insert(tk.END, "[*] Prompting for password via pkexec...\n\n")
                else:
                    self.output_text.insert(tk.END, "[*] Prompting for password via sudo...\n\n")
                self.root.update()

                return subprocess.Popen(
                    elevated_cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    universal_newlines=True,
                    bufsize=1
                )
        except Exception as e:
            raise Exception(f"Failed to elevate privileges: {str(e)}")

    def _run_scan(self, cmd):
        """Execute the scan in a separate thread"""
        try:
            # Check if sudo/admin is needed
            needs_elevation = self._needs_sudo(cmd)

            if needs_elevation:
                self.process = self._run_with_elevation(cmd)

                if self.process is None:  # Windows case
                    self.output_text.insert(tk.END,
                        "\n[!] Please run the command above in an elevated command prompt.\n")
                    self.status_var.set("Waiting for manual execution")
                    self.is_running = False
                    self.scan_button.config(state=tk.NORMAL)
                    self.stop_button.config(state=tk.DISABLED)
                    return
            else:
                self.process = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    universal_newlines=True,
                    bufsize=1
                )

            for line in self.process.stdout:
                if not self.is_running:
                    self.process.terminate()
                    break
                self.output_text.insert(tk.END, line)
                self.output_text.see(tk.END)
                self.root.update()

            self.process.wait()

            if self.is_running:
                self.status_var.set("Scan completed successfully")
            else:
                self.status_var.set("Scan stopped by user")

        except Exception as e:
            self.output_text.insert(tk.END, f"\nError: {str(e)}\n")
            self.status_var.set(f"Error: {str(e)}")

        finally:
            self.is_running = False
            self.scan_button.config(state=tk.NORMAL)
            self.stop_button.config(state=tk.DISABLED)
            self.process = None

    def _stop_scan(self):
        """Stop the running scan"""
        if self.process:
            self.process.terminate()
            self.is_running = False
            self.status_var.set("Stopping scan...")

    def _clear_output(self):
        """Clear the output text"""
        self.output_text.delete(1.0, tk.END)
        self.status_var.set("Ready")

    def _copy_command(self):
        """Copy the command to clipboard"""
        cmd_text = self.command_display.get(1.0, tk.END).strip()
        if cmd_text:
            self.root.clipboard_clear()
            self.root.clipboard_append(cmd_text)
            messagebox.showinfo("Copied", "Command copied to clipboard!")


def main():
    root = tk.Tk()
    app = NmapGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()
